#!/usr/bin/env python3
"""Turn a web page into a spreadsheet, driven entirely by a config file.

You do not edit this file. You edit a job file in jobs/ and run:

    python3 scrape.py jobs/example.toml

If you don't know which selectors to put in the job file, run this first
and it will suggest them:

    python3 scrape.py --inspect "https://example.com/page"

Needs: pip install requests beautifulsoup4 openpyxl
"""

from __future__ import annotations

import argparse
import csv
import re
import sys
import time
import tomllib
import urllib.parse
import urllib.robotparser
from collections import Counter
from pathlib import Path

try:
    import requests
    from bs4 import BeautifulSoup
except ImportError:
    sys.exit("Missing libraries. Run:  pip install requests beautifulsoup4 openpyxl")

UA = "Mozilla/5.0 (compatible; DataExtractBot/1.0)"
TIMEOUT = 30


# ---------- plain-language errors ----------

def die(msg: str, hint: str = "") -> None:
    print(f"\n[STOPPED] {msg}", file=sys.stderr)
    if hint:
        print(f"          {hint}", file=sys.stderr)
    sys.exit(1)


# ---------- fetching ----------

def robots_allows(url: str) -> bool | None:
    """True/False, or None when robots.txt cannot be read at all."""
    parts = urllib.parse.urlparse(url)
    robots = f"{parts.scheme}://{parts.netloc}/robots.txt"
    rp = urllib.robotparser.RobotFileParser()
    try:
        r = requests.get(robots, headers={"User-Agent": UA}, timeout=15)
        if r.status_code != 200:
            return None
        rp.parse(r.text.splitlines())
        return rp.can_fetch(UA, url)
    except requests.RequestException:
        return None


def fetch(url: str) -> BeautifulSoup:
    try:
        r = requests.get(url, headers={"User-Agent": UA}, timeout=TIMEOUT)
    except requests.Timeout:
        die(f"The site took longer than {TIMEOUT}s to answer.",
            "It may be slow or blocking us. Try again, or raise delay_seconds.")
    except requests.RequestException as e:
        die(f"Could not reach {url}", f"({e.__class__.__name__}) Check the URL is right.")

    if r.status_code == 404:
        die(f"Page not found (404): {url}", "Check the URL — it may have changed.")
    if r.status_code in (403, 401):
        die(f"The site refused us ({r.status_code}).",
            "It is blocking automated access. Tell the client this one is not doable.")
    if r.status_code == 429:
        die("The site says we are asking too fast (429).",
            "Raise delay_seconds in the job file and run it again.")
    if r.status_code >= 400:
        die(f"The site returned an error ({r.status_code}).")

    return BeautifulSoup(r.text, "html.parser")


# ---------- inspect: find selectors for you ----------

def describe(el) -> str:
    """A CSS selector that identifies this element's kind."""
    classes = [c for c in (el.get("class") or []) if not re.search(r"\d", c)]
    return el.name + ("." + ".".join(classes[:2]) if classes else "")


def inspect(url: str) -> int:
    print(f"Looking at {url}\n")

    allowed = robots_allows(url)
    if allowed is False:
        print("!! robots.txt asks bots NOT to fetch this page.")
        print("   Decline this job, or ask the client to confirm they have permission.\n")
    elif allowed is None:
        print("-- Could not read robots.txt. Check the site's terms yourself.\n")
    else:
        print("ok robots.txt allows this page.\n")

    soup = fetch(url)

    # Repeated sibling elements are almost always the rows of a listing.
    counts: Counter = Counter()
    for el in soup.find_all(True):
        if el.get("class") and len(el.find_all(True)) >= 2:
            counts[describe(el)] += 1

    good = [(sel, n) for sel, n in counts.most_common(40) if 3 <= n <= 500]
    if not good:
        print("Could not find repeating rows. The page may build its content with")
        print("JavaScript, which this tool cannot read. Decline the job.")
        return 1

    print("Likely row_selector values — the one matching the number of items you")
    print("can see on the page is the right one:\n")

    for sel, n in good[:8]:
        print(f"  row_selector = \"{sel}\"      ({n} matches)")
        sample = soup.select_one(sel)
        if not sample:
            continue
        for child in list(sample.find_all(True))[:6]:
            text = " ".join(child.get_text(" ", strip=True).split())[:52]
            if text:
                print(f"        {describe(child):<28} -> {text}")
            # Links and images are usually wanted as the URL, not the text,
            # so offer that form too rather than only when there is no text.
            if child.name == "a" and child.get("href"):
                print(f"        {describe(child) + '@href':<28} -> {child['href'][:52]}")
            elif child.name == "img" and child.get("src"):
                print(f"        {describe(child) + '@src':<28} -> {child['src'][:52]}")
        print()

    print("Copy the one you want into a job file, then put the inner lines under")
    print("[columns]. Add @href or @src to grab a link or image instead of text.")
    return 0


# ---------- extract ----------

def value_of(row, spec: str) -> str:
    """spec is "css" for text, or "css@attr" for an attribute."""
    sel, _, attr = spec.partition("@")
    el = row.select_one(sel.strip()) if sel.strip() else row
    if el is None:
        return ""
    if attr:
        return str(el.get(attr.strip(), "")).strip()
    return " ".join(el.get_text(" ", strip=True).split())


def run_job(path: Path) -> int:
    if not path.exists():
        die(f"No job file at {path}", "Copy jobs/example.toml and edit it.")

    try:
        with path.open("rb") as fh:
            job = tomllib.load(fh)
    except tomllib.TOMLDecodeError as e:
        die(f"The job file has a typo: {e}",
            "Every text value needs quotes around it, like url = \"https://...\"")

    for key in ("url", "row_selector", "columns"):
        if key not in job:
            die(f"The job file is missing: {key}", "Compare it against jobs/example.toml")
    if not job["columns"]:
        die("No columns listed.", "Add at least one line under [columns].")

    opts = job.get("options", {})
    pages = int(opts.get("pages", 1))
    delay = float(opts.get("delay_seconds", 2))
    out = Path(opts.get("output", f"out/{path.stem}.csv"))
    page_param = opts.get("page_param", "?page={n}")

    allowed = robots_allows(job["url"])
    if allowed is False and not opts.get("i_have_permission", False):
        die("robots.txt asks bots not to fetch this page.",
            "Decline the job, or set i_have_permission = true only if the client\n"
            "          genuinely owns the site or has written permission.")

    headers = list(job["columns"].keys())
    rows: list[dict] = []

    for n in range(1, pages + 1):
        url = job["url"] if n == 1 else job["url"] + page_param.format(n=n)
        print(f"  page {n}/{pages} ...", end=" ", flush=True)

        soup = fetch(url)
        found = soup.select(job["row_selector"])
        print(f"{len(found)} rows")

        if not found:
            if n == 1:
                die(f"row_selector \"{job['row_selector']}\" matched nothing.",
                    f"Run:  python3 scrape.py --inspect \"{job['url']}\"")
            break  # ran past the last page

        for el in found:
            rows.append({h: value_of(el, job["columns"][h]) for h in headers})

        if n < pages:
            time.sleep(delay)

    if not rows:
        die("No data extracted.")

    # Duplicates usually mean pagination looped back to page 1.
    seen, unique = set(), []
    for r in rows:
        k = tuple(r.values())
        if k not in seen:
            seen.add(k)
            unique.append(r)
    if len(unique) < len(rows):
        print(f"  removed {len(rows) - len(unique)} duplicate rows")

    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", newline="", encoding="utf-8-sig") as fh:
        w = csv.DictWriter(fh, fieldnames=headers)
        w.writeheader()
        w.writerows(unique)

    written = [out]
    if str(out).endswith(".csv") and opts.get("also_xlsx", True):
        try:
            from openpyxl import Workbook
            wb = Workbook()
            ws = wb.active
            ws.title = "Data"
            ws.append(headers)
            for r in unique:
                ws.append([r[h] for h in headers])
            for i, h in enumerate(headers, 1):
                width = max(len(h), *(len(r[h]) for r in unique)) + 2
                ws.column_dimensions[ws.cell(1, i).column_letter].width = min(width, 60)
            ws.freeze_panes = "A2"
            xlsx = out.with_suffix(".xlsx")
            wb.save(xlsx)
            written.append(xlsx)
        except ImportError:
            print("  (openpyxl not installed — CSV only)")

    blank = [h for h in headers if all(not r[h] for r in unique)]
    if blank:
        print(f"\n  !! These columns came out empty: {', '.join(blank)}")
        print("     Their selectors are probably wrong. Re-run --inspect.")

    print(f"\nDone. {len(unique)} rows.")
    for f in written:
        print(f"  {f}")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("job", nargs="?", help="path to a job file, e.g. jobs/example.toml")
    ap.add_argument("--inspect", metavar="URL", help="suggest selectors for a page")
    args = ap.parse_args()

    if args.inspect:
        return inspect(args.inspect)
    if not args.job:
        ap.print_help()
        return 1
    return run_job(Path(args.job))


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except KeyboardInterrupt:
        sys.exit("\nStopped.")
